version: '1.0'
env: node

build:
  cmd: npm install

start:
  cmd: npm start
  preview:
    branch: feature  

services:
- name: app
  port: 2005
  env:
    CLOUD_NAME: dwncoz80h
    CLOUDINARY_API_KEY: 565431864745684
    CLOUDINARY_API_SECRET: -j9R4BM_Ld2EQk0wJXpr1oYqxpo
    DB_REMOTE= mongodb+srv: mongo:mongo1234@cluster0.rkd734d.mongodb.net/?retryWrites=true&w=majority

